services:
  jekyll-server:
    build: .
    image: "anatole:dev"
    container_name: anatole-container
    ports:
      - "4000:4000"
    volumes:
      - .:/home/juser/jekyll-theme-anatole
    working_dir: /home/juser/jekyll-theme-anatole
    stdin_open: true
    tty: true
    command: "/bin/ash"
