services:
  jekyll-server:
    build: .
    image: "anatole:dev"
    container_name: anatole-container
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    stdin_open: true
    tty: true
    command: "/bin/ash"
